url: https://agilex-book-club.github.io
baseurl: 

# Site settings
title: NoVa Developers Club
email: tmuxvim@gmail.com
description: "The club meets every Saturday to learn a new programming language and create applications based on the language"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00aaa6
  secondary: 727272  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Rob Simpson
  pic: 1
  position: Web Developer
  social:
    - title: twitter
      url: http://www.twitter.com/pertrai1
    - title: github
      url: https://github.com/pertrai1
    - title: linkedin
      url: http://www.linkedin.com/in/rsimpson2

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/pertrai1
  - title: github
    url: https://github.com/nova-developers/nova-developers.github.io

# Build settings
markdown: kramdown
permalink: pretty
