url: https://agilex-book-club.github.io
baseurl: 

# Site settings
title: Agilex Book Club
email: tmuxvim@gmail.com
description: "This book club meets every Saturday for an hour or two to discuss details of the current book that the club is reading. The books are focused on different programming languages"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00aaa6
  secondary: 727272  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Rob Simpson
  pic: 1
  position: Web Developer
  social:
    - title: twitter
      url: http://www.twitter.com/pertrai1
    - title: linkedin
      url: #

- name: Sid Bhatia
  pic: 2
  position: Software Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/pertrai1
  - title: github
    url: http://github.com/pertrai1

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
